name: EduardLIB
description: API de desenvolvimento de plugins que facilita sua vida
main: net.eduard.api.lib.EduardLIB
version: 2.3
author: Eduard
authors: [Eduard]
soft-depend: [Essentials,Vault,McMMO]
website: https://www.youtube.com/user/EduTutoriaisHD
